### ISSUE TITLE
Working in editor but just hangs silently on webgl build

### ISSUE THREAD

**Issue by achia** [transformsai/UnityGrpcWeb#1]
Tried both async and normal calls with 0.3.4 and 2020.3.24f1 and .net 2.0 and .net4x. Just spinning ball unfortunately after the preflight network request returns 200

**Comment by MHDante** [comment]
Can you please post a minimal snippet of the code you used to connect? Also, what server/proxy are you using?

**Comment by achia** [comment]
Sure thing!

AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport",
true);
GrpcChannel channel = UnityGrpcWeb.MakeChannel("
https://MyServerGoesHere.azurewebsites.net");
var commsClient = new ProtoService.ProtoServiceClient(channel);

As you can see I'm using an azure app service with a DotNet ASP 6.0 kestrel
server with GRPC Web enabled.

builder.Services.AddGrpc();
builder.Services.AddCors(o => o.AddPolicy("AllowAll", builder =>
{
    builder.AllowAnyOrigin()
           .AllowAnyMethod()
           .AllowAnyHeader()
           .WithExposedHeaders("Grpc-Status", "Grpc-Message",
"Grpc-Encoding", "Grpc-Accept-Encoding", "X-Grpc-Web", "User-Agent");

}));

//further on down

app.UseCors("AllowAll");
app.UseGrpcWeb();
app.MapGrpcService<ProtoService>().EnableGrpcWeb().RequireCors("AllowAll");

**Comment by achia** [comment]
I think I had this line because I was testing the server as local host on a mac and required it before I switched to azure app service hosted, but changing/removing it doesnt seem to make a difference.

AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport",
true);

**Comment by MHDante** [comment]
Cool, and just to confirm: you installed this package through OpenUPM?

**Comment by MHDante** [comment]
The other thing I would appreciate is the code you use to execute the call (where you await the response).

**Comment by achia** [comment]
Yes via OpenUPM. Works perfectly in unityeditor with unary calls both sync and async, but silently freezes on a webgl build in both chrome and firefox on mac.

 var reply = commsClient.CompleteBattle(new Request
            {
                WalletID = GetWalletID()
            });

This also works in editor but doesnt work on webgl build

 var reply = commsClient.CompleteBattleAsync(new Request
            {
                WalletID = GetWalletID()
            }).GetAwaiter().GetResult();

**Comment by achia** [comment]
If you've got any ideas I'm all ears and willing to try a fix. Otherwise I'm about to throw in the towel and go back to REST API >.<

**Comment by MHDante** [comment]
Synchronous calls are not supported in WebGL since it is a singlethreaded platform (for now).

You need to await the result of the call asynchronously. I would strongly recommend using Async/Await, but you can do so with callbacks:

async/await version:
```csharp

async void CompleteBattle(){

    var reply =await commsClient.CompleteBattleAsync(new Request{WalletID = GetWalletID()});

    // Note that this happens on a separate frame from the previous line
    Debug.Log(reply.SomeValue);
}
```


callback version:

```csharp
commsClient.CompleteBattleAsync(new Request{WalletID = GetWalletID()}) 
    .ResponseAsync.ContinueWith(reply =>
        {
            // Note that this happens on a separate frame
            Debug.Log(reply.SomeValue);
        });   
```

**Comment by MHDante** [comment]
Let me know if this works, and I can close this issue (also tagging https://github.com/grpc/grpc-dotnet/issues/1309 ) to leave a breadcrumb

I'm sorry I've been too busy to write docs :(

**Comment by achia** [comment]
No worries! And thanks for getting back on this.

I'm right in the middle of switching back over to REST API as I figured
it'd be safer in the long run. But if I get a long break in the next few
weeks/months I'll put the whole environment back on and test.

Sorry to be the butterfly, but I appreciate the pointers and will come back
to this. In the meantime happy to close the issue!
