### ISSUE TITLE
ReferenceError: Runtime is not defined

### ISSUE THREAD

**Issue by fayf** [transformsai/UnityGrpcWeb#4]
When trying to use the code in WebGL, I get the following error:
```
ReferenceError: Runtime is not defined
    oac http://localhost:59741/Build/grpc-test-client.framework.js:2049
    get reference http://localhost:59741/Build/grpc-test-client.framework.js:48
    ...
```

`Runtime.dynCall` seems to have been replaced by `dynCall`, but even when I try to modify `JsLibGenerator` to generate the code correctly, the application blocks and freezes when it gets to the code point which uses `dynCall`.

**Comment by MHDante** [comment]
Thanks for the report, what version of Unity are you using?

**Comment by fayf** [comment]
I'm using 2021.3.9f1.

**Comment by anhnguyenvn** [comment]
@fayf can I ask you a question...
Do you know how to use this repo code in Unity?

**Comment by kokoro-aya** [comment]
I have encountered the same problem. For the `Runtime is not defined` it could be solved by the solution here:
https://stackoverflow.com/questions/70411564/unity-webgl-throws-error-referenceerror-runtime-is-not-defined

This requires to install the package manually to be able to change the .jslib file.

Still under a 2021.3 Unity version it will trigger another error which says an uncaught error was thrown in the promise.

**Comment by KShoukry** [comment]
@fayf Have you tried @kokoro-aya 's linked solution? Did it work for you? If so could you please share the code with us?
