### ISSUE TITLE
Incompatible with Unity 2021.3? 

### ISSUE THREAD

**Issue by kokoro-aya** [transformsai/UnityGrpcWeb#5]
I had set up a demo under version 2021.3.11f1, the project compiles and was shown in browser without any problem.

However once a gRPC call is launched I got the following error:

`localhost/:1 Uncaught (in promise) <with a random number>` 

![PromiseError](https://user-images.githubusercontent.com/35118912/197150298-679b222d-0b99-46fa-a554-f76d14668f6f.png)

The connection was established and browser retrieved the remote stuff with a 200 code and a payload.

Downgrading to Unity 2020 (2020.3.40f1 for me) could resolve this issue.

**Comment by MHDante** [comment]
This is likely fixed by: https://github.com/transformsai/UnityGrpcWeb/issues/4

**Comment by MHDante** [comment]
This is likely fixed by: https://github.com/transformsai/UnityWebGLInterop/pull/2

Will take a little bit to upstream dependencies.

**Comment by MHDante** [comment]
I believe @KShoukry 's recent change has solved this issue in 0.3.5
